name: Publish on GitHub Pages

on:
  pull_request:
    branches: [main]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    environment: github-pages
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Setup Deno environment
        uses: denoland/setup-deno@v2

      - name: Generate .env file
        run: >
          echo """RUNTIME_ENV=production""" >> .env
          && echo """CMS_ADMIN_PASSWORD=${{secrets.CMS_ADMIN_PASSWORD}}""" >> .env

      - name: Build GitHub Pages with Lume
        uses: lumeland/build/gh-pages@main
        with:
          cmd: deno task install && deno task build
